### importing libraries

In [2]:
import numpy as np


### loading data and making one hot vector

In [3]:
d=np.loadtxt("C:/Users/Naman/Desktop/ml dl/data1.csv",delimiter=",",dtype=int)
l=np.loadtxt("C:/Users/Naman/Desktop/ml dl/label1.csv",delimiter=",",dtype=int,ndmin=2)
print(d.shape)
print(l.shape)
print(d)
values=np.max(l)+1
hot=np.eye(values)[l]
hot=np.reshape(hot,(20000,5))
print(hot)
print(hot.shape)


#train test split is not done to avoid the needless effort
#

(20000, 20)
(20000, 1)
[[ 0  0  0 ...  0  1  0]
 [ 0 -1  0 ...  0 -1  0]
 [-1  0  0 ...  1 -1  0]
 ...
 [ 0  1  0 ...  0  0  0]
 [-1  0  0 ...  0  0  1]
 [ 1  0 -1 ...  0  1  1]]
[[0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 ...
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]]
(20000, 5)


# generating weights

In [4]:
np.random.seed(1)
w1=np.random.random((20,2))
w2=np.random.random((2,5))   ##number of neurons in mid layer is fixed i.e.,2

# activation function and its derivative

In [5]:
def sigmoid(x,der=False):
        if(der==True):
            return x*(1-x)
        return 1/(1+np.exp(-x))

# forward pass and backward pass

In [6]:
for i in range(5):
    a0=d     ##forward pass
    a1=sigmoid(np.dot(a0,w1))
    a2=sigmoid(np.dot(a1,w2))

    
    err2=hot-a2       #backward pass
    delta2=err2*sigmoid(a2,der=True)
    err1=delta2.dot(w2.T)
    delta1=err1*sigmoid(a1,der=True)
    
    
    w2 +=a1.T.dot(delta2)  #updatation of weights
    w1 +=a0.T.dot(delta1)

print(a2)
print(hot)

[[0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.  0.  0.  0.  0. ]
 ...
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.  0.  0.  0.  0. ]]
[[0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 ...
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]]


In [7]:
print(a2) #ouput after 10 epochs

[[0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.  0.  0.  0.  0. ]
 ...
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.  0.  0.  0.  0. ]]
